name: CI Model Tests

on:
  push:
    branches:
      - "epic/modeling"
  pull_request:
    branches:
      - "epic/modeling"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./transformer_e2e

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run tests
        run: |
          pytest
