name: Modeling Branch CI

on:
  push:
    branches:
      - epic/modeling # triggers on pushes to this branch
  pull_request:
    branches:
      - epic/modeling # triggers on PRs targeting this branch

jobs:
  lint-and-test: # run linters and unit tests
    runs-on: ubuntu-latest # use github's ubuntu virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # pull the repo code from github into the virtual machine

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # installs python 3.11 in the runner environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Lint with black
        run: black --check . # checks if all python files are properly formatted
        # does not reformat the files, the job fails if file is not compliant

      - name: Check style with flake8 # ensures code follows PEP8 style guidelines
        run: flake8 . # fails the job if too long lines, unused imports

      - name: Type check with mypy # uses python type hints to catch type mismatch between function arguments and return types
        run: mypy .

      - name: Run unit tests # runs all test cases defined in tests/
        run: pytest tests/

      - name: Run inference smoke test # runs a small script to run a few prompts after loading trained model
        run: python tests/smoke_inference_test.py
